# version: '3.8'

# services:
#   backend:
#     build: ./bigclasses_backend/backend
#     ports:
#       - "8000:8000"
#     volumes:
#       - ./bigclasses_backend/backend:/app
#     command: python manage.py runserver 0.0.0.0:8000

#   frontend:
#     build: ./bigclasses.ai
#     ports:
#       - "8080:80"
#     depends_on:
#       - backend

version: '3.8'

services:
  backend:
    build: ./bigclasses_backend/backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./bigclasses_backend/backend:/app
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build: ./bigclasses.ai
    container_name: frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
